version: '3'

services:
  app:
    build: .
    container_name: 'api-easyecom'
    volumes:
      - .:/usr/app
    ports:
      - 3777:3777
    command: sh ./exec.sh
    depends_on:
      - db
    networks:
      - overlay
  db:
    image: postgres:alpine
    container_name: db-easyecom
    networks:
      - overlay
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_NAME: ${DATABASE_NAME}
    restart: on-failure
      
networks:
    overlay:
