version: "3.8"

services:
  app:
    build: .
    container_name: "sid"
    command: npm run dev
    ports:
      - "3777:3777"
    networks:
      - overlay
    depends_on:
      - db
    volumes:
      - .:/usr/app
  db:
    image: 'postgres:latest'
    container_name: "sid-database"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - /var/lib/postgresql/data 
    networks:
      - overlay
    ports:
      - "5434:5432"
networks:
  overlay: