exports.seed = function(knex) {
    // Deletes ALL existing entries
    return knex('addresses')
        .del()
        .then(function() {
            // Inserts seed entries
            return knex('addresses').insert([
                {
                    addressId: 1,
                    zipcode: '015598-491',
                    street: 'francisco rodrigues filho',
                    number: '222',
                    complement: 'casa',
                    neighborhood: '11',
                    city: 'mogilandia',
                    state: 'São Paulo',
                    state_code: 'sp',
                    country: 'Brasil',
                    user_id: 1,
                    store_id: 1,
                },
                {
                    addressId: 2,
                    zipcode: '015598-491',
                    street: 'francisco rodrigues filho',
                    number: '222',
                    complement: 'casa',
                    neighborhood: '11',
                    city: 'mogilandia',
                    state: 'São Paulo',
                    state_code: 'sp',
                    country: 'Brasil',
                    user_id: 2,
                    store_id: 1,
                },
                {
                    addressId: 3,
                    zipcode: '015598-491',
                    street: 'Rua Hebe Ackel',
                    number: '222',
                    complement: 'casa',
                    neighborhood: '11',
                    city: 'pimentolandia',
                    state: 'Guarulhos',
                    state_code: 'sp',
                    country: 'Brasil',
                    user_id: 3,
                    store_id: 1,
                },
                {
                    addressId: 4,
                    zipcode: '015598-491',
                    street: 'Rua do Pedroso',
                    number: '222',
                    complement: 'casa',
                    neighborhood: '11',
                    city: 'Grazyelolandia',
                    state: 'Suzano',
                    state_code: 'sp',
                    country: 'Brasil',
                    user_id: 4,
                    store_id: 1,
                },
                {
                    addressId: 5,
                    zipcode: '015598-491',
                    street: 'Rua Diomar Ackel',
                    number: '222',
                    complement: 'casa',
                    neighborhood: '11',
                    city: 'Pimentolandia',
                    state: 'Guarulhos',
                    state_code: 'sp',
                    country: 'Brasil',
                    user_id: 5,
                    store_id: 2,
                },
                {
                    addressId: 6,
                    zipcode: '014698-491',
                    street: 'Rua Miguel Ackel',
                    number: '222',
                    complement: 'casa',
                    neighborhood: '11',
                    city: 'Groelandia',
                    state: 'Guarulhos',
                    state_code: 'sp',
                    country: 'Brasil',
                    user_id: 6,
                    store_id: 2,
                },
                {
                    addressId: 7,
                    zipcode: '015598-491',
                    street: 'Rua Diomar Ackel',
                    number: '222',
                    complement: 'casa',
                    neighborhood: '11',
                    city: 'Velhazelandia',
                    state: 'Guarulhos',
                    state_code: 'sp',
                    country: 'Brasil',
                    user_id: 7,
                    store_id: 2,
                },
                {
                    addressId: 8,
                    zipcode: '018938-491',
                    street: 'Rua Diomar Ackel',
                    number: '222',
                    complement: 'casa',
                    neighborhood: '11',
                    city: 'Caracolandia',
                    state: 'São Paulo',
                    state_code: 'sp',
                    country: 'Brasil',
                    user_id: 8,
                    store_id: 2,
                },
            ]);
        });
};
