exports.seed = function(knex) {
    // Deletes ALL existing entries
    return knex('variations')
        .del()
        .then(function() {
            // Inserts seed entries
            return knex('variations').insert([
                {
                    variationId: 1,
                    variationName: 'bermuda nike cinza',
                    isActive: true,
                    keyWords: 'calcados, sapatos, tenis, skate',
                    title: 'bermuda muito legal',
                    descriptionShort: 'bermuda muito legal',
                    description: 'bermuda muito legal',
                    packagedHeight: '177',
                    packagedLength: '190',
                    packagedWidth: '240',
                    weightKg: '2',
                    freeShipping: false,
                    amount: 1,
                    costPrice: 10,
                    offerPrice: 99,
                    salesPrice: 120,
                    product_id: 1,
                    store_id: 1,
                },
                {
                    variationId: 2,
                    variationName: 'calça adidas verde',
                    isActive: true,
                    keyWords: 'calcados, sapatos, tenis, skate',
                    title: 'calça muito legal',
                    descriptionShort: 'calça muito legal',
                    description: 'calça muito legal',
                    packagedHeight: '177',
                    packagedLength: '190',
                    packagedWidth: '240',
                    weightKg: '2',
                    freeShipping: false,
                    amount: 3,
                    costPrice: 120,
                    offerPrice: 0,
                    salesPrice: 180,
                    product_id: 2,
                    store_id: 1,
                },
                {
                    variationId: 3,
                    variationName: 'bolsa morena rosa marrom',
                    isActive: true,
                    keyWords: 'calcados, sapatos, tenis, skate, bolsas',
                    title: 'bolsa muito legal',
                    descriptionShort: 'bolsa muito legal',
                    description: 'bolsa muito legal',
                    packagedHeight: '177',
                    packagedLength: '190',
                    packagedWidth: '240',
                    weightKg: '2',
                    freeShipping: false,
                    amount: 12,
                    costPrice: 300,
                    offerPrice: 399,
                    salesPrice: 450,
                    product_id: 3,
                    store_id: 2,
                },
                {
                    variationId: 4,
                    variationName: 'blusa bad girls azul',
                    isActive: true,
                    keyWords: 'calcados, sapatos, tenis, skate',
                    title: 'blusa muito legal',
                    descriptionShort: 'blusa muito legal',
                    description: 'blusa muito legal',
                    packagedHeight: '177',
                    packagedLength: '190',
                    packagedWidth: '240',
                    weightKg: '2',
                    freeShipping: false,
                    amount: 6,
                    costPrice: 80,
                    offerPrice: 0,
                    salesPrice: 129,
                    product_id: 4,
                    store_id: 2,
                },
            ]);
        });
};
